# Generated by Django 3.1.2 on 2021-06-10 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210610_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 10, 6, 58, 42, 431145, tzinfo=utc)),
        ),
    ]
