# Generated by Django 3.1.2 on 2021-06-14 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210610_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
