# Generated by Django 3.1.2 on 2021-05-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(default='', max_length=5000)),
                ('name', models.CharField(default='', max_length=5000)),
                ('email', models.EmailField(default='', max_length=5000)),
                ('address', models.CharField(default='', max_length=2000)),
                ('city', models.CharField(default='', max_length=70)),
                ('state', models.CharField(default='', max_length=700)),
                ('Zip_code', models.IntegerField(default='', max_length=700)),
                ('Phone_No', models.IntegerField(max_length=20)),
            ],
        ),
    ]
