# Generated by Django 3.1.2 on 2021-05-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210529_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Phone_No',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Zip_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
